# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sinicynaleksej/4ISMA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sinicynaleksej/4ISMA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sinicynaleksej/4ISMA/CMakeFiles /Users/sinicynaleksej/4ISMA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sinicynaleksej/4ISMA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 4isma

# Build rule for target.
4isma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 4isma
.PHONY : 4isma

# fast build rule for target.
4isma/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/build
.PHONY : 4isma/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/main.cpp.s
.PHONY : main.cpp.s

runned/Button.o: runned/Button.cpp.o
.PHONY : runned/Button.o

# target to build an object file
runned/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/runned/Button.cpp.o
.PHONY : runned/Button.cpp.o

runned/Button.i: runned/Button.cpp.i
.PHONY : runned/Button.i

# target to preprocess a source file
runned/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/runned/Button.cpp.i
.PHONY : runned/Button.cpp.i

runned/Button.s: runned/Button.cpp.s
.PHONY : runned/Button.s

# target to generate assembly for a file
runned/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/runned/Button.cpp.s
.PHONY : runned/Button.cpp.s

runned/insur.o: runned/insur.cpp.o
.PHONY : runned/insur.o

# target to build an object file
runned/insur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/runned/insur.cpp.o
.PHONY : runned/insur.cpp.o

runned/insur.i: runned/insur.cpp.i
.PHONY : runned/insur.i

# target to preprocess a source file
runned/insur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/runned/insur.cpp.i
.PHONY : runned/insur.cpp.i

runned/insur.s: runned/insur.cpp.s
.PHONY : runned/insur.s

# target to generate assembly for a file
runned/insur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/runned/insur.cpp.s
.PHONY : runned/insur.cpp.s

runned/usrs.o: runned/usrs.cpp.o
.PHONY : runned/usrs.o

# target to build an object file
runned/usrs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/runned/usrs.cpp.o
.PHONY : runned/usrs.cpp.o

runned/usrs.i: runned/usrs.cpp.i
.PHONY : runned/usrs.i

# target to preprocess a source file
runned/usrs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/runned/usrs.cpp.i
.PHONY : runned/usrs.cpp.i

runned/usrs.s: runned/usrs.cpp.s
.PHONY : runned/usrs.s

# target to generate assembly for a file
runned/usrs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4isma.dir/build.make CMakeFiles/4isma.dir/runned/usrs.cpp.s
.PHONY : runned/usrs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 4isma"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... runned/Button.o"
	@echo "... runned/Button.i"
	@echo "... runned/Button.s"
	@echo "... runned/insur.o"
	@echo "... runned/insur.i"
	@echo "... runned/insur.s"
	@echo "... runned/usrs.o"
	@echo "... runned/usrs.i"
	@echo "... runned/usrs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

